### ISSUE TITLE
Dependency Issue : AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

### ISSUE THREAD

**Issue by khanfarhan10** [khanfarhan10/LungSegmentationCustomUNET#2]
(LungUNETCPUEnv) G:\GitLab\LungSegmentationCustomUNET>python lungunetmodel_new.py
2021-05-24 03:30:09.604590: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-05-24 03:30:09.605214: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using TensorFlow backend.
Traceback (most recent call last):
  File "lungunetmodel_new.py", line 19, in <module>
    from keras import backend as keras
  File "G:\GitLab\LungSegmentationCustomUNET\LungUNETCPUEnv\lib\site-packages\keras\__init__.py", line 12, in <module>
    from . import initializers
  File "G:\GitLab\LungSegmentationCustomUNET\LungUNETCPUEnv\lib\site-packages\keras\initializers\__init__.py", line 124, in <module>
    populate_deserializable_objects()
  File "G:\GitLab\LungSegmentationCustomUNET\LungUNETCPUEnv\lib\site-packages\keras\initializers\__init__.py", line 82, in populate_deserializable_objects
    generic_utils.populate_dict_with_module_objects(
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

**Comment by khanfarhan10** [comment]
@nirmalya8 can you see this?
